config/routes.rb
Rails.application.routes.draw do

  

  
  mount RailsAdmin::Engine => '/admin', as: :rails_admin
  mount Piggybak::Engine => '/shop/checkout', as: :piggybak
  mount PiggybakTaxonomy::Engine => '/shop', :as => 'piggybak_taxonomy'
  mount PiggybakCoupons::Engine => '/shop', :as => 'piggybak_coupons'
  mount PiggybakGiftcerts::Engine => '/shop', :as => 'piggybak_giftcerts'
  mount PiggybakBundleDiscounts::Engine => '/shop', :as => 'piggybak_bundle_discounts'
    
  

  
  resources :profile_pictures, only: [ :create ]

  get 'users/:id/chat' => 'messages#index'
  
  
  devise_for :users

  
  get '/chat' => 'conversations#index'
  

  

  resources :conversations do
    resources :messages
  end

  get 'users/:id' => 'users#show', as: :user
  resources :posts do
  	resources :comments
  	resources :about    
      	
  end

  
  	
  root "posts#index"

  resources :upload 
  get '/about', to: 'pages#about' 
  get '/beehive', to: 'pages#beehive'
  get '/personal_page', to: 'pages#personal_page'
  get '/forum', to: 'forumposts#index'
  get '/avatar', to: 'pages#index'


  
  resources :forumposts do
    resources :forumcomments
  end  

  
  get '/shop', to: 'products#index'

  resources :products
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    if user && user.roles.include?(Role.find_by_name("admin"))
      can :dashboard
      can :access, :rails_admin
      can [:read, :edit]
      can :manage, :all
      can :manage, Piggybak.config.manage_classes.map(&:constantize)
      Piggybak.config.extra_abilities.each do |extra_ability|
          can extra_ability[:abilities], extra_ability[:class_name].constantize
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable 


  def self.find_for_database_authentication warden_conditions
	conditions = warden_conditions.dup
	login = conditions.delete(:login)
	where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end
  
end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  has_one :profile_picture
  attribute :filename
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts

end	

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

end

app/models/conversation.rb
class Conversation < ApplicationRecord
	
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/models/forumcomment.rb
class Forumcomment < ApplicationRecord
  belongs_to :forumpost
  belongs_to :user
end

app/models/forumpost.rb
class Forumpost < ApplicationRecord
	belongs_to :user
	has_many :forumcomments
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
  
end

app/models/option.rb
class Option < ApplicationRecord
	belongs_to :optable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :category  
	has_many :comments, dependent: :destroy 
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true
	resourcify
	
end

app/models/product.rb
class Product < ApplicationRecord
	acts_as_sellable
	
end

app/models/profilepicture.rb
class ProfilePicture < ActiveRecord::Base
  belongs_to :user
  belongs_to :avatar
  attribute :user_id 
  attribute :avatar_id

  
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	
	mount_uploader :userfile, UserfileUploader

	def userfile
	end	
end

app/models/user.rb
class User < ApplicationRecord
  

  rolify :before_add => :before_add_method
  belongs_to :role, optional: true
  has_one :profile_picture
  has_one :avatar, through: :profile_picture
  

  


  def before_add_method(role)
    # do something before it gets added
    assign_default_role
  end


  
  def admin?
    user_id == 1 # If you have id == 0 for admin
  end


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :username, presence: true 

  has_many :conversations, :foreign_key => :sender_id       
 
  

  
  attr_accessor :login  

  has_many :comments
  has_many :forumposts
  has_many :forumcomments
  has_many :products

  acts_as_orderer

  private

    def assign_default_role
      self.add_role(:newuser) if self.roles.blank?      
    end


     

    def user_params
      params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :role, :avatar)
    end

    

    def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :check_authorization, only: [:edit, :update]
  before_action :set_user, only: [:edit, :update]

  attr_accessor  :email, :username

  
  def show
  	@user = User.find(params[:id])
  end

  def create

    @user = User.new(user[:newuser])
    @user.add_role(:newuser)

      if @user.save
        redirect_to root_path, :notice => "Welcome to To Bee family!"
      else
        render "new"
      end
  end


  def index
    @users = User.all
  end

  def new
    @user = User.new
  end


  def edit    
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      flash.now[:alert] =  "Something went wrong. Hope you don't mind trying again!"
      render :edit
    end
  end  

  def can?
  end

  def cannot?
  end 

  private
    def check_authorization
      unless current_user.id == params[:id].to_i
        redirect_to root_url
      end
    end    

    def set_user
     @user = User.find(params[:id])
    end  

    def user_params
      params.require(:user).permit(:id, :username, :role, :user_id, :email, :password, :password_confirmation, :upload )
    end

end

app/helpers/honeys_helper.rb
module HoneysHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/users_helper.rb
module UsersHelper

	
end

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    
  	<title>To Bee</title>
	
	   <%= stylesheet_link_tag 'user_show', media: 'all', 'data-turbolinks-track'=> "reload" %>

   </head>	
  <body class= "user_container">


    <div class="vertical-menu">
      <a> <%= link_to "Personal", current_user, :class=>"active"%></a>
      <a> <%= link_to "Chat", conversations_path %></a>
      <a> <%= link_to "Forum", forum_path %></a>
      <a> <%= link_to "Shop", shop_path %></a>
      <a> <%= link_to "Upload", "upload#index" %></a>
    </div> 

    <%= link_to root_path do %>
      <div id="home_logo">          
          <img><%= image_tag "TOBEE logo 280.png" %></img>   
      </div>   
    <% end %> 

    <% if user_signed_in? %>
              <div class="ui_buttons">
                <% if current_user.has_role? :admin %>
                  <%= link_to new_post_path do %>                       
                      <img class= 'ui_button'><%= image_tag "new post.png"%></img>   
                  <% end %>
                <% end %>
                <%= link_to destroy_user_session_path do %>                       
                    <img class= 'ui_button'><%= image_tag "log out.png"%></img>   
                <% end %>
                
                
              </div>
        
      <% end%>

          
      

    <div id="background_container">
      <div class="user_content">
      <img src="">
        <p><h3> Edit Profile, <%= @user.username %>!</h3></p>
        <%= form_for(@user, html: { multipart: true }) do |f| %>
    			<%= f.label :username %><br />
    			<%= f.text_field :username %><br />

    			<%= f.file_field :avatar %><br />
  			
  			  <%= f.submit "Save Changes" %><br />
        <% end %>

      <small>To Bee Beehive</small>
      </div>
     
     
       
    </div>
    



  </body>
</html>  

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    
  	<title>To Bee</title>
	
	   <%= stylesheet_link_tag    'user_show', media: 'all', 'data-turbolinks-track'=> "reload" %>

   </head>	
  <body class= "user_container">


    <div class="vertical-menu">
      <a> <%= link_to "Personal", current_user, :class=>"active"%></a>
      <a> <%= link_to "Chat", conversations_path %></a>
      <a> <%= link_to "Forum", forum_path %></a>
      <a> <%= link_to "Shop", shop_path %></a>
      <a> <%= link_to "Upload", "upload#index" %></a>
    </div> 

    <%= link_to root_path do %>
      <div id="home_logo">          
          <img><%= image_tag "TOBEE logo 280.png" %></img>   
      </div>   
    <% end %> 

      <% if user_signed_in? %>
              <div class="ui_buttons">
                <% if current_user.has_role? :admin %>
                  <%= link_to new_post_path do %>                       
                      <img class= 'ui_button'><%= image_tag "new post.png"%></img>   
                  <% end %>
                <% end %>
                <%= link_to destroy_user_session_path do %>                       
                    <img class= 'ui_button'><%= image_tag "log out.png"%></img>   
                <% end %>                
              </div>
              <%= link_to current_user do %>
                  <div id="ui_avatar">           
                        
                  </div>                   
              <% end %>
        
      <% end%>

          
      

    <div id="background_container">
      <div class="user_content">
      <img src="">
        <p><h3>Welcome back, <%= @user.username %>!</h3>
        Your introducing: <br/>
        <br/>
        This is your personal user area, where you can edit your account details, update personal profile, post and read other users' posts in the forum area, upload different files for Liondeer to see, buy or just check out different To Bee products and hit up chat to chit chat with other bees. Enjoy, we are happy to have you here!</p>
        
      <small>To Bee Beehive</small>
      </div>
     
     
       
    </div>
    <%= link_to "Edit account ", edit_user_registration_path , :class=> "btn-oldschool" , :type=>"button"%>

    <%= link_to "Edit personal page ", "" , :class=> "btn-oldschool" , :type=>"button"%>




  </body>
</html>  