config/routes.rb
Rails.application.routes.draw do

  

  
  mount RailsAdmin::Engine => '/admin', as: :rails_admin
  mount Piggybak::Engine => '/shop/checkout', as: :piggybak
  mount PiggybakTaxonomy::Engine => '/shop', :as => 'piggybak_taxonomy'
  mount PiggybakCoupons::Engine => '/shop', :as => 'piggybak_coupons'
  mount PiggybakGiftcerts::Engine => '/shop', :as => 'piggybak_giftcerts'
  mount PiggybakBundleDiscounts::Engine => '/shop', :as => 'piggybak_bundle_discounts'
    
  

  
  resources :profile_pictures, only: [ :create ]

  get 'users/:id/chat' => 'messages#index'
  
  
  devise_for :users

  
  get '/chat' => 'conversations#index'
  

  

  resources :conversations do
    resources :messages
  end

  get 'users/:id' => 'users#show', as: :user
  resources :posts do
  	resources :comments
  	resources :about    
      	
  end

  
  	
  root "posts#index"

  resources :upload 
  get '/about', to: 'pages#about' 
  get '/beehive', to: 'pages#beehive'
  get '/personal_page', to: 'pages#personal_page'
  get '/forum', to: 'forumposts#index'
  get '/avatar', to: 'pages#index'


  
  resources :forumposts do
    resources :forumcomments
  end  

  
  get '/shop', to: 'products#index'

  resources :products
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    if user && user.roles.include?(Role.find_by_name("admin"))
      can :dashboard
      can :access, :rails_admin
      can [:read, :edit]
      can :manage, :all
      can :manage, Piggybak.config.manage_classes.map(&:constantize)
      Piggybak.config.extra_abilities.each do |extra_ability|
          can extra_ability[:abilities], extra_ability[:class_name].constantize
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable 


  def self.find_for_database_authentication warden_conditions
	conditions = warden_conditions.dup
	login = conditions.delete(:login)
	where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end
  
end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  has_one :profile_picture
  attribute :filename
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts

end	

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

end

app/models/conversation.rb
class Conversation < ApplicationRecord
	
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/models/forumcomment.rb
class Forumcomment < ApplicationRecord
  belongs_to :forumpost
  belongs_to :user
end

app/models/forumpost.rb
class Forumpost < ApplicationRecord
	belongs_to :user
	has_many :forumcomments
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
  
end

app/models/option.rb
class Option < ApplicationRecord
	belongs_to :optable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :category  
	has_many :comments, dependent: :destroy 
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true
	resourcify
	
end

app/models/product.rb
class Product < ApplicationRecord
	acts_as_sellable
	
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	
	mount_uploader :userfile, UserfileUploader

	def userfile
	end	
end

app/models/user.rb
class User < ApplicationRecord
  

  rolify :before_add => :before_add_method
  belongs_to :role, optional: true
  has_one :profile_picture
  has_one :avatar, through: :profile_picture
  

  


  def before_add_method(role)
    # do something before it gets added
    assign_default_role
  end


  
  def admin?
    user_id == 1 # If you have id == 0 for admin
  end


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :username, presence: true 

  has_many :conversations, :foreign_key => :sender_id       
 
  

  
  attr_accessor :login  

  has_many :comments
  has_many :forumposts
  has_many :forumcomments
  has_many :products

  acts_as_orderer

  private

    def assign_default_role
      self.add_role(:newuser) if self.roles.blank?      
    end


     

    def user_params
      params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :role, :avatar)
    end

    

    def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout "product", except: [:index, :rss]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :must_be_admin, only: [:edit, :new, :create, :update, :destroy]


  def index
    @products = Product.all.order("created_at DESC") 
  end 

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end  

  def create
    
    @product = Product.new(product_params)

    if @product.save!
      flash[:notice] = "Successfully created product!"
      redirect_to shop_path
    else
      render 'new'
    end 
  end   

  def edit
    @product = Product.find(params[:id])  
  end 
  
  def update
    @product = Product.find(params[:id])

    if @product.update(params[:product].permit(:name, :description, :id))
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    
    @product.destroy
    redirect_to shop_path
  end


  private  

  def product_params
    params.require(:product).permit(:name, :description)
  end 

  def must_be_admin
    unless current_user.has_role? :admin
      redirect_to root_path, notice: "Access Denied, Sorry!"
    end
  end

end

		

app/helpers/honeys_helper.rb
module HoneysHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/users_helper.rb
module UsersHelper

	
end

app/views/products/_form.html.haml
!!!
%html
%head
	%title To Bee Shop
	= stylesheet_link_tag    'store', media: 'all', 'data-turbolinks-track' => true
	%link{ rel: "stylesheet", href: "http://fonts.googleapis.com/css?family=Lato:300,400,700", type: "text/css"}
	%link{:rel => "stylesheet", :href => "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css"}/
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body.product_form
	#sidebar{ style: 'display: none;' }  

	= simple_form_for @product do |f|
		= f.label :name
		= f.text_area :name, :class => "tinymce", :rows => 1, :cols => 120
		= f.label :description
		= f.text_area :description, :class => "tinymce", :rows => 6, :cols => 120 
		%br/
		= f.submit

	 


	= tinymce :alternate 

app/views/products/edit.html.haml
!!!
%html
%head

    %title To Bee Shop
    = stylesheet_link_tag    'store', media: 'all', 'data-turbolinks-track' => true
    %link{ rel: "stylesheet", href: "http://fonts.googleapis.com/css?family=Lato:300,400,700", type: "text/css"}
    %link{:rel => "stylesheet", :href => "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css"}/
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %script type="text/javascript" src="/assets/tinymce/js/tinymce/tinymce.js"
%body.product_form   

    %h1 Edit Product

    = render 'form'

    = link_to "Cancel", shop_path

    

app/views/products/index.html.haml
!!!
%html
%head
    %title To Bee Shop
    = javascript_include_tag "store"
    = stylesheet_link_tag    'store', media: 'all', 'data-turbolinks-track' => true


%body.store_body    
    %div#container
        #arrow-left.arrow
        #slider
            .slide.slide1
                .slide-content
                    #logo 
                        = link_to image_tag('TOBEE logo 280.png'), root_path, :class => "shop_logo"
                    %span Desk Organizer
                    %p1 Made by Lõvi
                    #storeBtn{:onclick => "bottomFunction()"}
                        = image_tag 'down arrow.png', :class => "shop_arrow" 
                    
                    #product_info 
                        = link_to image_tag('index.png'), root_path, :class => "photo_detail_1" 
                        = link_to image_tag('index.png'), root_path, :class => "photo_detail_2" 
                        = link_to image_tag('index.png'), root_path, :class => "photo_detail_3" 
                        = link_to image_tag('index.png'), root_path, :class => "photo_detail_4" 
                        %p2 "Recte, inquit, intellegis.An est aliquid per se ipsum flagitiosum, etiamsi nulla comitetur infamia?Sullae consulatum?   Hoc dixerit potius Ennius: Nimium boni est, cui nihil est mali.   Eiuro, inquit adridens, iniquum, hac quidem de re; Cur igitur, cum de re conveniat, non malumus usitate loqui? Et si in ipsa gubernatione neglegentia est navis eversa, maius est peccatum in auro quam in palea. Neque solum ea communia, verum etiam paria esse dixerunt. Est igitur officium eius generis, quod nec in bonis ponatur nec in contrariis. Idemne potest esse dies saepius, qui semel fuit? Habes, inquam, Cato, formam eorum, de quibus loquor, philosophorum. Eorum enim omnium multa praetermittentium, dum eligant aliquid, quod sequantur, quasi curta sententia;     Graecis hoc modicum est: Leonidas, Epaminondas, tres aliqui aut quattuor; Hoc Hieronymus summum bonum esse dixit. Iam enim adesse poterit. Dat enim intervalla et relaxat. Ratio enim nostra consentit, pugnat oratio. Quorum sine causa fieri nihil putandum est. Nam illud vehementer repugnat, eundem beatum esse et multis malis oppressum. Utrum igitur tibi litteram videor an totas paginas commovere?" 
                        %p3  "Recte, inquit, intellegis.An est aliquid per se ipsum flagitiosum, etiamsi nulla comitetur infamia?Sullae consulatum?   Hoc dixerit potius Ennius: Nimium boni est, cui nihil est mali.   Eiuro, inquit adridens, iniquum, hac quidem de re; Cur igitur, cum de re conveniat, non malumus usitate loqui? Et si in ipsa gubernatione neglegentia est navis eversa, maius est peccatum in auro quam in palea. Neque solum ea communia, verum etiam paria esse dixerunt. Est igitur officium eius generis, quod nec in bonis ponatur nec in contrariis. Idemne potest esse dies saepius, qui semel fuit? Habes, inquam, Cato, formam eorum, de quibus loquor, philosophorum. Eorum enim omnium multa praetermittentium, dum eligant aliquid, quod sequantur, quasi curta sententia;     Graecis hoc modicum est: Leonidas, Epaminondas, tres aliqui aut quattuor; Hoc Hieronymus summum bonum esse dixit. Iam enim adesse poterit. Dat enim intervalla et relaxat. Ratio enim nostra consentit, pugnat oratio. Quorum sine causa fieri nihil putandum est. Nam illud vehementer repugnat, eundem beatum esse et multis malis oppressum. Utrum igitur tibi litteram videor an totas paginas commovere?"
                        %p4 Soon in Stock




            .slide.slide2
                .slide-content
                    #logo 
                        = link_to image_tag('TOBEE logo 280.png'), root_path, :class => "shop_logo"
                    %span To Bee Collar Shirt
                    %p1 Made by Lõvi
                    #storeBtn{:onclick => "bottomFunction()"}
                        = image_tag 'down arrow.png', :class => "shop_arrow" 
                    #product_info 
                        = link_to image_tag('index.png'), root_path, :class => "photo_detail_1" 
                        = link_to image_tag('index.png'), root_path, :class => "photo_detail_2" 
                        = link_to image_tag('index.png'), root_path, :class => "photo_detail_3" 
                        = link_to image_tag('index.png'), root_path, :class => "photo_detail_4" 
                        %p2 "Recte, inquit, intellegis.An est aliquid per se ipsum flagitiosum, etiamsi nulla comitetur infamia?Sullae consulatum?   Hoc dixerit potius Ennius: Nimium boni est, cui nihil est mali.   Eiuro, inquit adridens, iniquum, hac quidem de re; Cur igitur, cum de re conveniat, non malumus usitate loqui? Et si in ipsa gubernatione neglegentia est navis eversa, maius est peccatum in auro quam in palea. Neque solum ea communia, verum etiam paria esse dixerunt. Est igitur officium eius generis, quod nec in bonis ponatur nec in contrariis. Idemne potest esse dies saepius, qui semel fuit? Habes, inquam, Cato, formam eorum, de quibus loquor, philosophorum. Eorum enim omnium multa praetermittentium, dum eligant aliquid, quod sequantur, quasi curta sententia;     Graecis hoc modicum est: Leonidas, Epaminondas, tres aliqui aut quattuor; Hoc Hieronymus summum bonum esse dixit. Iam enim adesse poterit. Dat enim intervalla et relaxat. Ratio enim nostra consentit, pugnat oratio. Quorum sine causa fieri nihil putandum est. Nam illud vehementer repugnat, eundem beatum esse et multis malis oppressum. Utrum igitur tibi litteram videor an totas paginas commovere?" 
                        %p3  "Recte, inquit, intellegis.An est aliquid per se ipsum flagitiosum, etiamsi nulla comitetur infamia?Sullae consulatum?   Hoc dixerit potius Ennius: Nimium boni est, cui nihil est mali.   Eiuro, inquit adridens, iniquum, hac quidem de re; Cur igitur, cum de re conveniat, non malumus usitate loqui? Et si in ipsa gubernatione neglegentia est navis eversa, maius est peccatum in auro quam in palea. Neque solum ea communia, verum etiam paria esse dixerunt. Est igitur officium eius generis, quod nec in bonis ponatur nec in contrariis. Idemne potest esse dies saepius, qui semel fuit? Habes, inquam, Cato, formam eorum, de quibus loquor, philosophorum. Eorum enim omnium multa praetermittentium, dum eligant aliquid, quod sequantur, quasi curta sententia;     Graecis hoc modicum est: Leonidas, Epaminondas, tres aliqui aut quattuor; Hoc Hieronymus summum bonum esse dixit. Iam enim adesse poterit. Dat enim intervalla et relaxat. Ratio enim nostra consentit, pugnat oratio. Quorum sine causa fieri nihil putandum est. Nam illud vehementer repugnat, eundem beatum esse et multis malis oppressum. Utrum igitur tibi litteram videor an totas paginas commovere?"
                        %p4 Soon in Stock

            .slide.slide3
                .slide-content
                    #logo 
                        = link_to image_tag('TOBEE logo 280.png'), root_path, :class => "shop_logo"
                    %span To Bee Patch
                    %p1 Made by Lõvi
                    #storeBtn{:onclick => "bottomFunction()"}
                        = image_tag 'down arrow.png', :class => "shop_arrow" 
                    #product_info 
                        = link_to image_tag('index.png'), root_path, :class => "photo_detail_1" 
                        = link_to image_tag('index.png'), root_path, :class => "photo_detail_2" 
                        = link_to image_tag('index.png'), root_path, :class => "photo_detail_3" 
                        = link_to image_tag('index.png'), root_path, :class => "photo_detail_4" 
                        %p2 "Recte, inquit, intellegis.An est aliquid per se ipsum flagitiosum, etiamsi nulla comitetur infamia?Sullae consulatum?   Hoc dixerit potius Ennius: Nimium boni est, cui nihil est mali.   Eiuro, inquit adridens, iniquum, hac quidem de re; Cur igitur, cum de re conveniat, non malumus usitate loqui? Et si in ipsa gubernatione neglegentia est navis eversa, maius est peccatum in auro quam in palea. Neque solum ea communia, verum etiam paria esse dixerunt. Est igitur officium eius generis, quod nec in bonis ponatur nec in contrariis. Idemne potest esse dies saepius, qui semel fuit? Habes, inquam, Cato, formam eorum, de quibus loquor, philosophorum. Eorum enim omnium multa praetermittentium, dum eligant aliquid, quod sequantur, quasi curta sententia;     Graecis hoc modicum est: Leonidas, Epaminondas, tres aliqui aut quattuor; Hoc Hieronymus summum bonum esse dixit. Iam enim adesse poterit. Dat enim intervalla et relaxat. Ratio enim nostra consentit, pugnat oratio. Quorum sine causa fieri nihil putandum est. Nam illud vehementer repugnat, eundem beatum esse et multis malis oppressum. Utrum igitur tibi litteram videor an totas paginas commovere?" 
                        %p3  "Recte, inquit, intellegis.An est aliquid per se ipsum flagitiosum, etiamsi nulla comitetur infamia?Sullae consulatum?   Hoc dixerit potius Ennius: Nimium boni est, cui nihil est mali.   Eiuro, inquit adridens, iniquum, hac quidem de re; Cur igitur, cum de re conveniat, non malumus usitate loqui? Et si in ipsa gubernatione neglegentia est navis eversa, maius est peccatum in auro quam in palea. Neque solum ea communia, verum etiam paria esse dixerunt. Est igitur officium eius generis, quod nec in bonis ponatur nec in contrariis. Idemne potest esse dies saepius, qui semel fuit? Habes, inquam, Cato, formam eorum, de quibus loquor, philosophorum. Eorum enim omnium multa praetermittentium, dum eligant aliquid, quod sequantur, quasi curta sententia;     Graecis hoc modicum est: Leonidas, Epaminondas, tres aliqui aut quattuor; Hoc Hieronymus summum bonum esse dixit. Iam enim adesse poterit. Dat enim intervalla et relaxat. Ratio enim nostra consentit, pugnat oratio. Quorum sine causa fieri nihil putandum est. Nam illud vehementer repugnat, eundem beatum esse et multis malis oppressum. Utrum igitur tibi litteram videor an totas paginas commovere?"
                        %p4 Soon in Stock

            #arrow-right.arrow
             

        :javascript
            let sliderImages = document.querySelectorAll(".slide"),
              arrowLeft = document.querySelector("#arrow-left"),
              arrowRight = document.querySelector("#arrow-right"),
              current = 0;

            // Clear all images
            function reset() {
              for (let i = 0; i < sliderImages.length; i++) {
                sliderImages[i].style.display = "none";
              }
            }

            // Init slider
            function startSlide() {
              reset();
              sliderImages[0].style.display = "block";
            }

            // Show prev
            function slideLeft() {
              reset();
              sliderImages[current - 1].style.display = "block";
              current--;
            }

            // Show next
            function slideRight() {
              reset();
              sliderImages[current + 1].style.display = "block";
              current++;
            }

            // Left arrow click
            arrowLeft.addEventListener("click", function() {
              if (current === 0) {
                current = sliderImages.length;
              }
              slideLeft();
            });

            // Right arrow click
            arrowRight.addEventListener("click", function() {
              if (current === sliderImages.length - 1) {
                current = -1;
              }
              slideRight();
            });

            startSlide();

            
            function bottomFunction() {
                document.body.scrollTop = 580; 
                document.documentElement.scrollTop = 580; 
            } 




           

app/views/products/new.html.haml
!!!
%html
%head
	%title To Bee Shop
	= stylesheet_link_tag    'store', media: 'all', 'data-turbolinks-track' => true
	%link{ rel: "stylesheet", href: "http://fonts.googleapis.com/css?family=Lato:300,400,700", type: "text/css"}
	%link{:rel => "stylesheet", :href => "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css"}/
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body.product_form    

	= render 'form'

	= link_to "Cancel", shop_path

	

app/views/products/show.html.haml
!!!
%html
%head
	%title To Bee Shop
	= stylesheet_link_tag    'store', media: 'all', 'data-turbolinks-track' => true
	%link{ rel: "stylesheet", href: "http://fonts.googleapis.com/css?family=Lato:300,400,700", type: "text/css"}
	%link{:rel => "stylesheet", :href => "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css"}/
	= javascript_include_tag 'application', 'data-turbolinks-track' => false
	= csrf_meta_tags

%body.product_form

	#product_content	
		%h1= raw(@product.name)
		%p= raw(@product.description)


		


	= link_to "Edit", edit_product_path(@product)
	= link_to "Delete", product_path(@product), method: :delete, data: { confirm: "Are you sure about the 'delete'?"}
	= link_to "Store", shop_path

	